### ISSUE TITLE
Screenshots too small and out of date

### ISSUE THREAD

**Issue by quozl** [sugarlabs/dimensions#18]
* [ ] screenshots in this repository are not of the whole activity.
* [ ] screenshots in the [Help activity](https://help.sugarlabs.org/dimensions.html) show an older layout of the match area relative to the grid.

**Comment by quozl** [comment]
@walterbender, do you recall moving the match area under the grid and making the grid cells no longer line up?  This looks like a mistake when compared to the documentation.

![Screenshot_uff_2020-02-19_12:36:26](https://user-images.githubusercontent.com/2936481/74793451-7ffd9d00-5314-11ea-889a-02d6ac8e7961.png)

**Comment by quozl** [comment]
Never mind, unrelated.  Match area under grid happened in  f1dfbdd1a60311bdfd6ae8cae73b609a0d44fd27.  Diagonal grid is a regression.

**Comment by aryanharitsh123** [comment]
https://github.com/sugarlabs/dimensions/pull/22

**Comment by chimosky** [comment]
Closing as this was fixed in #22.
